server:
  port: 8888
eureka:
  instance:
    hostname: register8888.com
  client:
    serviceUrl:
    #     搭建注册中心集群模式使用 相互注册，互相守望
#      defaultZone: http://${eureka.instance.hostname}:9999/eureka/ 这么写不行，找到的是 register8888.com
      defaultZone: http://register9999.com:9999/eureka/
    #    false不把自己注册
    registerWithEureka: false
    #    false不扫描自己
    fetchRegistry: false

  server:
    # 开启自我保护 eureka 自我保护机制，默认开启，网络延时，当一台服务某一时刻不可用了，eureka不会立即删除，实际是 CAP（分区容错性） 中的 AP 高可用性，舍弃了一致性
    enableSelfPreservation: true
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000
spring:
  application:
    name: register-eureka