server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuan-chun/spring-cloud/    # 配置git仓库的地址
          search-paths: config-server                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: yuan-chun                                            # git仓库的账号
          password: zy521521.
