server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuan-chun/spring-cloud/
          search-paths: config-server
          username: yuan-chun
          password: zy521521.
