server:
  port: 9999
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
    #     搭建注册中心集群模式使用
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
    #    不把自己注册
    registerWithEureka: true
    #    不扫描自己
    fetchRegistry: true
spring:
  application:
    name: register-eureka